import CountrySelect from '../src/CountrySelect.vue';

new Vue({
    el: '#root-container',

    components: {
        'country-select': CountrySelect
    },

    data: {
        text: 'Выберите страну',
        countries: [
            {id:"AB", name:"Абхазия"},
            {id:"AU", name:"Австралия"},
            {id:"AT", name:"Австрия"},
            {id:"AZ", name:"Азербайджан"},
            {id:"AL", name:"Албания"},
            {id:"DZ", name:"Алжир"},
            {id:"AS", name:"Американское Самоа"},
            {id:"AI", name:"Ангилья"},
            {id:"AO", name:"Ангола"},
            {id:"AD", name:"Андорра"},
            {id:"AG", name:"Антигуа и Барбуда"},
            {id:"AR", name:"Аргентина"},
            {id:"AM", name:"Армения"},
            {id:"AW", name:"Аруба"},
            {id:"AF", name:"Афганистан"},
            {id:"BS", name:"Багамы"},
            {id:"BD", name:"Бангладеш"},
            {id:"BB", name:"Барбадос"},
            {id:"BH", name:"Бахрейн"},
            {id:"BY", name:"Беларусь"},
            {id:"BZ", name:"Белиз"},
            {id:"BE", name:"Бельгия"},
            {id:"BJ", name:"Бенин"},
            {id:"BM", name:"Бермуды"},
            {id:"BG", name:"Болгария"},
            {id:"BO", name:"Боливия"},
            {id:"BA", name:"Босния и Герцеговина"},
            {id:"BW", name:"Ботсвана"},
            {id:"BR", name:"Бразилия"},
            {id:"BN", name:"Бруней"},
            {id:"BF", name:"Буркина Фасо"},
            {id:"BI", name:"Бурунди"},
            {id:"BT", name:"Бутан"},
            {id:"VU", name:"Вануату"},
            {id:"VA", name:"Ватикан"},
            {id:"GB", name:"Великобритания"},
            {id:"HU", name:"Венгрия"},
            {id:"VE", name:"Венесуэла"},
            {id:"VG", name:"Виргинские Острова"},
            {id:"VN", name:"Вьетнам"},
            {id:"GA", name:"Габон"},
            {id:"HT", name:"Гаити"},
            {id:"GY", name:"Гайана"},
            {id:"GM", name:"Гамбия"},
            {id:"GH", name:"Гана"},
            {id:"GP", name:"Гваделупа"},
            {id:"GT", name:"Гватемала"},
            {id:"GN", name:"Гвинея"},
            {id:"GW", name:"Гвинея-Бисау"},
            {id:"DE", name:"Германия"},
            {id:"GG", name:"Гернси"},
            {id:"GI", name:"Гибралтар"},
            {id:"HN", name:"Гондурас"},
            {id:"HK", name:"Гонконг"},
            {id:"GD", name:"Гренада"},
            {id:"GL", name:"Гренландия"},
            {id:"GR", name:"Греция"},
            {id:"GE", name:"Грузия"},
            {id:"GU", name:"Гуам"},
            {id:"DK", name:"Дания"},
            {id:"JE", name:"Джерси"},
            {id:"DJ", name:"Джибути"},
            {id:"DM", name:"Доминика"},
            {id:"DO", name:"Доминиканская Республика"},
            {id:"CD", name:"ДР Конго"},
            {id:"EG", name:"Египет"},
            {id:"ZM", name:"Замбия"},
            {id:"EH", name:"Западная Сахара"},
            {id:"ZW", name:"Зимбабве"},
            {id:"IL", name:"Израиль"},
            {id:"IN", name:"Индия"},
            {id:"ID", name:"Индонезия"},
            {id:"JO", name:"Иордания"},
            {id:"IQ", name:"Ирак"},
            {id:"IR", name:"Иран"},
            {id:"IE", name:"Ирландия"},
            {id:"IS", name:"Исландия"},
            {id:"ES", name:"Испания"},
            {id:"IT", name:"Италия"},
            {id:"YE", name:"Йемен"},
            {id:"CV", name:"Кабо-Верде"},
            {id:"KZ", name:"Казахстан"},
            {id:"KY", name:"Каймановы Острова"},
            {id:"KH", name:"Камбоджа"},
            {id:"CM", name:"Камерун"},
            {id:"CA", name:"Канада"},
            {id:"QA", name:"Катар"},
            {id:"KE", name:"Кения"},
            {id:"CY", name:"Кипр"},
            {id:"KG", name:"Киргизия"},
            {id:"KI", name:"Кирибати"},
            {id:"CN", name:"Китай"},
            {id:"CO", name:"Колумбия"},
            {id:"KM", name:"Коморы"},
            {id:"CG", name:"Конго"},
            {id:"CR", name:"Коста-Рика"},
            {id:"CI", name:"Кот-д'Ивуар"},
            {id:"CU", name:"Куба"},
            {id:"KW", name:"Кувейт"},
            {id:"LA", name:"Лаос"},
            {id:"LV", name:"Латвия"},
            {id:"LS", name:"Лесото"},
            {id:"LR", name:"Либерия"},
            {id:"LB", name:"Ливан"},
            {id:"LY", name:"Ливия"},
            {id:"LT", name:"Литва"},
            {id:"LI", name:"Лихтенштейн"},
            {id:"LU", name:"Люксембург"},
            {id:"MU", name:"Маврикий"},
            {id:"MR", name:"Мавритания"},
            {id:"MG", name:"Мадагаскар"},
            {id:"MO", name:"Макао"},
            {id:"MK", name:"Македония"},
            {id:"MW", name:"Малави"},
            {id:"MY", name:"Малайзия"},
            {id:"ML", name:"Мали"},
            {id:"MV", name:"Мальдивы"},
            {id:"MT", name:"Мальта"},
            {id:"MA", name:"Марокко"},
            {id:"MQ", name:"Мартиника"},
            {id:"MH", name:"Маршалловы Острова"},
            {id:"MX", name:"Мексика"},
            {id:"FM", name:"Микронезия"},
            {id:"MZ", name:"Мозамбик"},
            {id:"MD", name:"Молдавия"},
            {id:"MC", name:"Монако"},
            {id:"MN", name:"Монголия"},
            {id:"MS", name:"Монтсеррат"},
            {id:"MM", name:"Мьянма"},
            {id:"NA", name:"Намибия"},
            {id:"NR", name:"Науру"},
            {id:"NP", name:"Непал"},
            {id:"NE", name:"Нигер"},
            {id:"NG", name:"Нигерия"},
            {id:"AN", name:"Нидерландские Антилы"},
            {id:"NL", name:"Нидерланды"},
            {id:"NI", name:"Никарагуа"},
            {id:"NZ", name:"Новая Зеландия"},
            {id:"NC", name:"Новая Каледония"},
            {id:"NO", name:"Норвегия"},
            {id:"AE", name:"ОАЭ"},
            {id:"OM", name:"Оман"},
            {id:"CK", name:"Острова Кука"},
            {id:"TC", name:"Острова Теркс и Кайкос"},
            {id:"IM", name:"Остров Мэн"},
            {id:"PK", name:"Пакистан"},
            {id:"PW", name:"Палау"},
            {id:"PS", name:"Палестинская территория"},
            {id:"PA", name:"Панама"},
            {id:"PG", name:"Папуа-Новая Гвинея"},
            {id:"PY", name:"Парагвай"},
            {id:"PE", name:"Перу"},
            {id:"PL", name:"Польша"},
            {id:"PT", name:"Португалия"},
            {id:"PR", name:"Пуэрто-Рико"},
            {id:"RE", name:"Реюньон"},
            {id:"RU", name:"Россия"},
            {id:"RW", name:"Руанда"},
            {id:"RO", name:"Румыния"},
            {id:"SV", name:"Сальвадор"},
            {id:"WS", name:"Самоа"},
            {id:"SM", name:"Сан-Марино"},
            {id:"ST", name:"Сан-Томе и Принсипи"},
            {id:"SA", name:"Саудовская аравия"},
            {id:"SZ", name:"Свазиленд"},
            {id:"KP", name:"Северная Корея"},
            {id:"SC", name:"Сейшелы"},
            {id:"SN", name:"Сенегал"},
            {id:"VC", name:"Сент-Винсент и Гренадины"},
            {id:"KN", name:"Сент-Китс и Невис"},
            {id:"LC", name:"Сент-Люсия"},
            {id:"RS", name:"Сербия"},
            {id:"SG", name:"Сингапур"},
            {id:"SY", name:"Сирия"},
            {id:"SK", name:"Словакия"},
            {id:"SI", name:"Словения"},
            {id:"SB", name:"Соломоновы острова"},
            {id:"SO", name:"Сомали"},
            {id:"SD", name:"Судан"},
            {id:"SR", name:"Суринам"},
            {id:"US", name:"США"},
            {id:"SL", name:"Сьерра-леоне"},
            {id:"TJ", name:"Таджикистан"},
            {id:"TH", name:"Таиланд"},
            {id:"TW", name:"Тайвань"},
            {id:"TZ", name:"Танзания"},
            {id:"TL", name:"Тимор-Лесте"},
            {id:"TG", name:"Того"},
            {id:"TO", name:"Тонга"},
            {id:"TT", name:"Тринидад и Тобаго"},
            {id:"TV", name:"Тувалу"},
            {id:"TN", name:"Тунис"},
            {id:"TM", name:"Туркмения"},
            {id:"TR", name:"Турция"},
            {id:"UG", name:"Уганда"},
            {id:"UZ", name:"Узбекистан"},
            {id:"UA", name:"Украина"},
            {id:"UY", name:"Уругвай"},
            {id:"FO", name:"Фарерские Острова"},
            {id:"FJ", name:"Фиджи"},
            {id:"PH", name:"Филиппины"},
            {id:"FI", name:"Финляндия"},
            {id:"FR", name:"Франция"},
            {id:"PF", name:"Французская Полинезия"},
            {id:"HR", name:"Хорватия"},
            {id:"CF", name:"ЦАР"},
            {id:"TD", name:"Чад"},
            {id:"ME", name:"Черногория"},
            {id:"CZ", name:"Чехия"},
            {id:"CL", name:"Чили"},
            {id:"CH", name:"Швейцария"},
            {id:"SE", name:"Швеция"},
            {id:"LK", name:"Шри-Ланка"},
            {id:"EC", name:"Эквадор"},
            {id:"GQ", name:"Экваториальная Гвинея"},
            {id:"ER", name:"Эритрея"},
            {id:"EE", name:"Эстония"},
            {id:"ET", name:"Эфиопия"},
            {id:"ZA", name:"Южная Африка"},
            {id:"KR", name:"Южная Корея"},
            {id:"OS", name:"Южная Осетия"},
            {id:"JM", name:"Ямайка"},
            {id:"JP", name:"Япония"}
        ]
    }
});